- id: looper
  alias: looper
  initial_state: true
  mode: restart
  trigger:
  - id: trigger_looper
    platform: state
    entity_id: input_boolean.activate_looper
    to: 'on'
  condition:
  - condition: trigger
    id: trigger_looper
  action:
  - repeat:
      while:
      - condition: or
        conditions:
        - condition: template
          value_template: '{% if is_state(''input_boolean.activate_looper'', ''on'')
            %} true {% else %} false {% endif %}'
      sequence:
      - service: persistent_notification.create
        data_template:
          title: Looper {{now().timestamp()|timestamp_local}}
          message: Looper has triggered.
      - delay: 00:00:01