- id: '1674727003374'
  alias: Timer
  description: ''
  trigger: []
  condition: []
  action:
  - service: timer.start
    data_template:
    entity_id: timer.cpap_timer
    duration: '{% set start = states(''input_datetime.cpap_ind_start_time'') %}  {%
      set start = as_timestamp([now().date() | string, start] | join('' '')) %} {%
      set end = start + 255 * 60 %} {{ (end - as_timestamp(now())) | timestamp_custom("%H:%M:00",
      false) }}

      '
  mode: single
- id: '1674733215050'
  alias: timer_ma_shelly_plug01
  description: ''
  trigger:
  - platform: state
    entity_id:
    - timer.ma_shelly_plug01_timer
    to: finished
  condition: []
  action: []
  mode: single
