# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# Default includes from Home Assistant
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#homeassistant:
  #packages:
    #common_device_tracker: !include common/device_tracker.yaml

recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 30
  purge_interval: 1
  commit_interval: 30 

history:

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_user
  password: !secret influxdb_pw
  ssl: false
  max_retries: 3
  default_measurement: state  
  measurement_attr: entity_id
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - input_number
      - button

input_text:
  ma_mushroomart_state:
    name: ma_mushroomart_state
    initial: State 5
    
# Add sliders control to Home Assistant to set position, speed and velocity of the stepper motor
input_number:
  ma_biolab_mushroomart_delay_01:
    name: ma_biolab_mushroomart_delay_01
    initial: 80
    min: 0
    max: 99999
    step: 1
    mode: box
  ma_biolab_mushroomart_delay_02:
    name: ma_biolab_mushroomart_delay_02
    initial: 80
    min: 0
    max: 99999
    step: 1
    mode: box
  ma_biolab_mushroomart_delay_03:
    name: ma_biolab_mushroomart_delay_03
    initial: 180
    min: 0
    max: 99999
    step: 1
    mode: box
  ma_biolab_mushroomart_delay_04:
    name: ma_biolab_mushroomart_delay_04
    initial: 120
    min: 0
    max: 99999
    step: 1
    mode: box
  ma_biolab_mushroomart_delay_05:
    name: ma_biolab_mushroomart_delay_05
    initial: 120
    min: 0
    max: 99999
    step: 1
    mode: box
  
  ma_hydrobag_pump_time_active:
    name: ma_hydrobag_pump_time_active
    initial: 1
    min: 0
    max: 1440
    step: 1
    mode: box
  
  ma_hydrobag_pump_time_pause:
    name: ma_hydrobag_pump_time_pause
    initial: 1
    min: 0
    max: 1440
    step: 1
    mode: box
   

#telegram_bot:
#  - platform: polling
#    api_key: "5326830285:AAEVnGd_oy2pvWxw6_GSXTy1MwsT6SKwIx8"
#    allowed_chat_ids:
#      - 133905357

# Example configuration.yaml entry for the notifier
#notify:
#  - platform: telegram
#    name: NOTIFIER_NAME
#    chat_id: 133905357
input_boolean:
  ma_shelly_plug01_is_power_comsuming:
    name: ma_shelly_plug01_is_power_comsuming
  
  ma_shelly_plug02_is_power_comsuming:
    name: ma_shelly_plug02_is_power_comsuming
    
  ma_shelly_plug03_is_power_comsuming:
    name: ma_shelly_plug03_is_power_comsuming
    
  ma_shelly_plug04_is_power_comsuming:
    name: ma_shelly_plug04_is_power_comsuming
    
  ma_biolab_mushroomart_automation_active:
    name: ma_biolab_mushroomart_automation_active
    
  ma_hydrobag_light_automation_active:
    name: ma_hydrobag_light_automation_active
  
  ma_hydrobag_pump_automation_active:
    name: ma_hydrobag_pump_automation_active
  
  ma_hydrobag_pump_enabled:
    name: ma_hydrobag_pump_enabled
  
  ma_hydrobag_light_enabled:
    name: ma_hydrobag_light_enabled
  
  ma_hydrobag_pump_active:
    name: ma_hydrobag_pump_active
    
  ma_microgreens_stack_1_automation_active:
    name: ma_microgreens_stack_1_automation_active
  
timer:
  test:
    duration: "01:30:00"
  ma_shelly_plug01_timer:
    duration: "01:30:00"
  ma_shelly_plug02_timer:
    duration: "01:30:00"
  ma_shelly_plug03_timer:
    duration: "01:30:00"
  ma_shelly_plug04_timer:
    duration: "01:30:00"
  ma_shelly_plug01_notification_timer:
    duration: "01:15:00"
  ma_shelly_plug02_notification_timer:
    duration: "01:15:00"
  ma_shelly_plug03_notification_timer:
    duration: "01:15:00"
  ma_shelly_plug04_notification_timer:
    duration: "01:15:00"
    
input_datetime:
  ma_shelly_plug01_timer_duration:
    name: ma_shelly_plug01_timer_duration
    has_time: true  
  
  ma_shelly_plug02_timer_duration:
    name: ma_shelly_plug02_timer_duration
    has_time: true  
  
  ma_shelly_plug03_timer_duration:
    name: ma_shelly_plug03_timer_duration
    has_time: true  
  
  ma_shelly_plug04_timer_duration:
    name: ma_shelly_plug04_timer_duration
    has_time: true  
  ma_shelly_plug01_notification_timer_duration:
    name: ma_shelly_plug01_notification_timer_duration
    has_time: true  
  
  ma_shelly_plug02_notification_timer_duration:
    name: ma_shelly_plug02_notification_timer_duration
    has_time: true  
  
  ma_shelly_plug03_notification_timer_duration:
    name: ma_shelly_plug03_notification_timer_duration
    has_time: true  
  
  ma_shelly_plug04_notification_timer_duration:
    name: ma_shelly_plug04_notification_timer_duration
    has_time: true  
    
  ma_hydrobag_automation_date_start:
    name: ma_hydrobag_automation_date_start
    has_date: true   
  
  ma_hydrobag_automation_date_end:
    name: ma_hydrobag_automation_date_end
    has_date: true  

        
sensor:
#####################
# Integration Sensors
#####################
  - platform: integration
    source: sensor.ma_shelly_plug01_power
    unit_prefix: k
    unit_time: h
    method: left
  
  - platform: integration
    source: sensor.ma_shelly_plug02_power
    unit_prefix: k
    unit_time: h
    method: left
    
  - platform: integration
    source: sensor.ma_shelly_plug03_power
    unit_prefix: k
    unit_time: h
    method: left
  
  - platform: integration
    source: sensor.ma_shelly_plug04_power
    unit_prefix: k
    unit_time: h
    method: left
    
#####################
# Average Sensors    
#####################
  - platform: statistics
    entity_id: sensor.ma_shelly_plug01_power
    state_characteristic: average_step
    sampling_size: 6
    max_age: 
      minutes: 2
    name: ma_shelly_plug01_power_average_step
  
  - platform: statistics
    entity_id: sensor.ma_shelly_plug02_power
    state_characteristic: average_step
    sampling_size: 6
    max_age: 
      minutes: 2
    name: ma_shelly_plug02_power_average_step
  
  - platform: statistics
    entity_id: sensor.ma_shelly_plug03_power
    state_characteristic: average_step
    sampling_size: 6
    max_age: 
      minutes: 2
    name: ma_shelly_plug03_power_average_step
  
  - platform: statistics
    entity_id: sensor.ma_shelly_plug04_power
    state_characteristic: average_step
    sampling_size: 6
    max_age: 
      minutes: 2
    name: ma_shelly_plug04_power_average_step


#####################
# Max Value Sensors    
#####################   
  - platform: statistics
    entity_id: sensor.ma_shelly_plug01_power
    state_characteristic: value_max
    sampling_size: 4
    max_age: 
      minutes: 2
    name: ma_shelly_plug01_power_value_max
  
  - platform: statistics
    entity_id: sensor.ma_shelly_plug02_power
    state_characteristic: value_max
    sampling_size: 4
    max_age: 
      minutes: 2
    name: ma_shelly_plug02_power_value_max
  
  - platform: statistics
    entity_id: sensor.ma_shelly_plug03_power
    state_characteristic: value_max
    sampling_size: 4
    max_age: 
      minutes: 2
    name: ma_shelly_plug03_power_value_max
  
  - platform: statistics
    entity_id: sensor.ma_shelly_plug04_power
    state_characteristic: value_max
    sampling_size: 4
    max_age: 
      minutes: 2
    name: ma_shelly_plug04_power_value_max

#####################
# Min Value Sensors    
#####################    
  - platform: statistics
    entity_id: sensor.ma_shelly_plug01_power
    state_characteristic: value_min
    sampling_size: 4
    max_age: 
      minutes: 2
    name: ma_shelly_plug01_power_value_min
  
  - platform: statistics
    entity_id: sensor.ma_shelly_plug02_power
    state_characteristic: value_min
    sampling_size: 4
    max_age: 
      minutes: 2
    name: ma_shelly_plug02_power_value_min
  
  - platform: statistics
    entity_id: sensor.ma_shelly_plug03_power
    state_characteristic: value_min
    sampling_size: 4
    max_age: 
      minutes: 2
    name: ma_shelly_plug03_power_value_min
  
  - platform: statistics
    entity_id: sensor.ma_shelly_plug04_power
    state_characteristic: value_min
    sampling_size: 4
    max_age: 
      minutes: 2
    name: ma_shelly_plug04_power_value_min   
    
    