# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# Default includes from Home Assistant
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  packages:
    common_device_tracker: !include common/device_tracker.yaml

#recorder:
#  db_url: !secret mariadb_url
#  purge_keep_days: 7
#  purge_interval: 1
#  commit_interval: 30 
#
#history:

#influxdb:
#  host: a0d7b954-influxdb
#  port: 8086
#  database: homeassistant
#  username: !secret influxdb_user
#  password: !secret influxdb_pw
#  ssl: false
#  max_retries: 3
#  default_measurement: state  
#  measurement_attr: entity_id
#  include:
#    domains:
#      - sensor
#      - binary_sensor
#      - switch
#      - input_number
#      - button

# Add sliders control to Home Assistant to set position, speed and velocity of the stepper motor
input_number: