version: '3'
services:
  esphome:
    container_name: esphome-dev
    image: esphome/esphome
    volumes:
      - /media/sf_Shared/esphome-dev/esphome:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host

