substitutions:
  #general settings
  host_name: empty-component
  device_name: empty_component
  device_name_upper: empty.component
  status_led_interval_ok: 10s
  status_led_interval_booting: 3s
  settings_log_level: VERBOSE
  activate_fast_connect: "true"
  api_reboot_timeout: "2min"
  
esphome:
  name: ${host_name}
  platform: ESP32
  board: esp32dev
  #board: nodemcu-32s

# Enable logging
logger:
  level: DEBUG
  
preferences:
  flash_write_interval: 1min
  
packages:
  common_api: !include /config/esphome/esphome-common/api.yaml
  common_base: !include /config/esphome/esphome-common/base.yaml
  common_status: !include /config/esphome/esphome-common/status.yaml
  common_restart: !include /config/esphome/esphome-common/restart.yaml