substitutions:
  #general settings
  host_name: sdg-cam1
  device_name: sdg_cam1
  device_name_upper: sdg.cam1
  status_led_pin: GPIO33
  status_led_interval_ok: 10s
  status_led_interval_booting: 3s
  settings_log_level: DEBUG
  settings_flash_write_interval: 1min
  settings_static_ip: ${settings_static_ip_pcs1_cam1}
  activate_fast_connect: "true"
  api_reboot_timeout: "2min"
  
  #i2c settings
  i2c_bus_b_name: bus_b
  i2c_bus_b_sda: GPIO13
  i2c_bus_b_scl: GPIO15 
  
  # ESP32cam settings
  esp32cam_flashlight_pin: GPIO04
  esp32cam_custom_idle_framerate: "0 fps"
  esp32cam_vertical_flip: "false"
  esp32cam_horizontal_mirror: "false"
  esp32cam_max_framerate: "1 fps"
  esp32cam_resolution: "1600x1200"
  
  #bme280_1 settings
  bme280_1_name: bme280_1
  bme280_1_i2c_bus: ${i2c_bus_b_name}
  bme280_1_oversampling: "16x"
  bme280_1_adress: "0x76"
  bme280_1_update_interval: "10s"
  
  #bmp280_2 settings
  bme280_2_name: bme280_2
  bme280_2_i2c_bus: ${i2c_bus_b_name}
  bme280_2_oversampling: "16x"
  bme280_2_adress: "0x77"
  bme280_2_update_interval: "10s"
  
  #bh1750_1 settings
  bh1750_1_name: bh1750_1
  bh1750_1_i2c_bus: ${i2c_bus_b_name}
  bh1750_1_adress: "0x23"
  bh1750_1_resolution: "0.5" 
  bh1750_1_measurement_duration: "69" 
  bh1750_1_update_interval: "10s"
  
esphome:
  name: ${host_name}
  platform: ESP32
  board: esp32dev
  #board: nodemcu-32s

# Enable logging
logger:
  level: DEBUG
  
preferences:
  flash_write_interval: 1min
  
packages:
  common_api: !include /config/esphome/esphome-common/api.yaml
  common_base: !include /config/esphome/esphome-common/base.yaml
  common_status: !include /config/esphome/esphome-common/status.yaml
  common_status_led: !include /config/esphome/esphome-common/status_led.yaml
  common_restart: !include /config/esphome/esphome-common/restart.yaml
  common_i2c_bus_b: !include /config/esphome/esphome-common/i2c_bus_b.yaml   
  camera_esp32cam: !include /config/esphome/esphome-camera/esp32cam.yaml
  sensors_bme280_1: !include /config/esphome/esphome-sensors/bme280_1.yaml
  #sensors_bme280_2: !include /config/esphome/esphome-sensors/bme280_2.yaml
  sensors_bh1750_1: !include /config/esphome/esphome-sensors/bh1750_1.yaml
  
  #camera_webserver: !include /config/esphome/esphome-camera/webserver_snapshot.yaml