substitutions:
  #general settings
  host_name: sdg-as1
  device_name: sdg_as1
  device_name_upper: sdg.as1
  status_led_interval_ok: 10s
  status_led_interval_booting: 3s
  settings_log_level: DEBUG
  settings_flash_write_interval: 1min
  
  # MQTT Settings
  mqtt_discovery: "false"
  
  #I2C Bus
  i2c_bus_a_name: i2c_bus_a
  i2c_bus_a_sda: GPIO23
  i2c_bus_a_scl: GPIO22

  # webserver
  web_server_ota_active: "true"
  
  # EZO settings
  max_retry_attempts: "4"
  default_temp_comp_value: "25"
  
  # EZO Enable Pins
  enable_rtd_pin: GPIO33
  enable_ec_pin: GPIO12
  enable_ph_pin: GPIO13
  
  # EZO sample intervals
  min_sample_interval_ec: "2000" # 1s
  max_sample_interval_ec: "10000" # 60min
  
  min_sample_interval_ph: "2000" # 1s
  max_sample_interval_ph: "10000" # 60min
  
  min_sample_interval_rtd: "1000" # 1s
  max_sample_interval_rtd: "10000" # 60min
  
  min_sample_interval_ec_tempcomp: "10000" 
  max_sample_interval_ec_tempcomp: "60000"
  
  min_sample_interval_ph_tempcomp: "10000" 
  max_sample_interval_ph_tempcomp: "60000"
  
  min_mqtt_interval_ec: "1000"
  max_mqtt_interval_ec: "3600000"
  
  min_mqtt_interval_ph: "1000"
  max_mqtt_interval_ph: "3600000"
  
  min_mqtt_interval_rtd: "1000"
  max_mqtt_interval_rtd: "3600000"
  
  entities_internal: "false"
  
  mqtt_rtd_enabled: "true"
  mqtt_ec_enabled: "true"
  mqtt_ph_enabled: "true"
  
  mqtt_entities_internal: "false"
  
# MQTT Broker Settings
mqtt:
  id: ${device_name}_mqtt_client
  broker: !secret njb_mqtt_broker_ip
  username: !secret njb_mqtt_usr
  password: !secret njb_mqtt_pw
  discovery: ${mqtt_discovery}
  port: !secret njb_mqtt_port

# enable ota updates
ota:
  password: !secret esphome_ota_pw

# Wifi Settings
wifi:
  networks:
  - ssid: !secret njb_wifi_ap_ssid
    password: !secret njb_wifi_ap_pw
    priority: 3
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$device_name_upper AP"
    password: !secret njb_esphome_fallback_ap_pw
  
  #fast_connect: true


captive_portal:

# Web server
web_server:
  port: !secret njb_web_server_port
  auth:
    username: !secret njb_web_server_user
    password: !secret njb_web_server_password
  ota: ${web_server_ota_active}
  
sensor:
  - platform: wifi_signal
    name: "${device_name_upper}.wifi_signal"
    id: ${device_name}_wifi_signal
    update_interval: 60s
    
esphome:
  name: ${host_name}
  platform: ESP32
  board: esp32dev
  #board: nodemcu-32s    
  
packages:
  common_time_sntp: !include /config/esphome/esphome-common/time_sntp.yaml
  common_logger: !include /config/esphome/esphome-common/logger.yaml
  common_preferences: !include /config/esphome/esphome-common/preferences.yaml
  common_status: !include /config/esphome/esphome-common/status.yaml
  common_restart: !include /config/esphome/esphome-common/restart.yaml
  common_i2c_bus_a: !include /config/esphome/esphome-common/i2c_bus_a.yaml
  as_hydroponics_kit_as_ezo: !include /config/esphome/esphome-ashydroponicskit/as_ezo.yaml
  as_hydroponics_kit_as_ezo_mqtt_sender: !include /config/esphome/esphome-ashydroponicskit/as_ezo_mqtt_sender.yaml